# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
A = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:

A = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack(A)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
A = np.arange(10).reshape(2,5)
B = np.arange(10, dtype = int).reshape(2,5)
print(A,B)
np.hstack((A,B))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:

import numpy as np
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
A = np.arange(15).reshape(1,3,5)
print(A.ndim, "dimensions")
print(A)
A = A.flatten()
print(A.ndim,  "dimension")
A

3 dimensions
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
1 dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
import numpy as np
a = np.arange(15).reshape(-1,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
import numpy as np
A = np.random.randn(5,5)
np.square(A)

array([[3.47566542e-02, 1.85087632e-01, 8.31199880e-02, 3.68498760e-01,
        3.48152182e-01],
       [7.32814405e-01, 3.25119481e+00, 7.93709734e-01, 8.81914042e-02,
        3.27396331e-01],
       [2.38538312e+00, 2.45220320e-02, 1.46773466e-01, 3.01068795e-04,
        1.10115180e-02],
       [2.17228568e-01, 3.07971246e-02, 1.34301172e-02, 2.60662990e-01,
        1.60826200e+00],
       [1.11865558e-01, 1.00495421e-01, 9.52345087e-01, 2.49871951e+00,
        9.69428467e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [9]:

np.random.seed(100)
A = np.random.randint(30, size =(5,6))
print(A)
C = A.mean()
print(C)

[[ 8 24  3  7 23 15]
 [16 10 20  2 21  2]
 [ 2 14  2 17 16 24]
 [15  4 11 28 26 16]
 [27  9 29 22  2 27]]
14.733333333333333


## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
np.std(C)

0.0

## Question:10

### Find the median of the previous array in Q8?

In [11]:
np.median(C)

14.733333333333333

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
print(A)
np.transpose(A)

[[ 8 24  3  7 23 15]
 [16 10 20  2 21  2]
 [ 2 14  2 17 16 24]
 [15  4 11 28 26 16]
 [27  9 29 22  2 27]]


array([[ 8, 16,  2, 15, 27],
       [24, 10, 14,  4,  9],
       [ 3, 20,  2, 11, 29],
       [ 7,  2, 17, 28, 22],
       [23, 21, 16, 26,  2],
       [15,  2, 24, 16, 27]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [22]:
A = np.arange(16).reshape(4,4)
print(A)
np.trace(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [24]:
np.linalg.det(A)



0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [20]:
A = np.arange(10)
print(A)
print(np.percentile(A, 5))
print(np.percentile(A, 95))

[0 1 2 3 4 5 6 7 8 9]
0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [21]:
A  = np.arange(10)
np.isnan(A)

array([False, False, False, False, False, False, False, False, False,
       False])